Repository pjbeltran/oxygen-cs-grp1-eq23, pull requests merged in 2023-11, with the labels that each got.

#26 Implémentation du pipeline CI
  .github/workflows/ci.yml
  src/main.py
  test/test.py
Labels: enhancement

#28 Bugfix/27 probleme avec les pre commit
  .github/hooks/pre-commit
  .pre-commit-config.yaml
  Pipfile
  Pipfile.lock
  src/main.py
  test/test.py
Labels: bug

#29 Doc/20 documentation
  doc/readme.md
Labels: documentation

#30 Correction du CI pour qu'il soit sur toutes les branche
  .github/workflows/ci.yml
  test/test.py
Labels: bug

#31 Création de la documentation sur le travail du Lab 2
  doc/readme.md
Labels: documentation

#32 Merge code vers main (Démo)
  .dockerignore
  .github/ISSUE_TEMPLATE/requête-fonctionnalité.md
  .github/ISSUE_TEMPLATE/signalement-de-bug.md
  .github/pull_request_template.md
  .github/workflows/ci.yml
  .pre-commit-config.yaml
  Dockerfile
  Pipfile
  Pipfile.lock
  README.md
  doc/app_start.png
  doc/event.png
  doc/readme.md
  doc/temp.png
  doc/tests.png
  doc/variables.png
  src/main.py
  test/test.py
Labels: enhancement
